#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,    HTSMux,         sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          sweeper,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          heartbeat,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     wheelC,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     wheelD,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     wheelB,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     wheelA,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     collectorMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     liftMotor,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    dumpServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    rightIRServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    leftIRServo,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "libAuto.c"


//variables for auto1
#define ONE_LEFT_DRIVE 4000
#define ONE_FORWARD_DRIVE 1850

//variables for auto2
#define TWO_SPIN 1200
#define TWO_LEFT 2750
#define TWO_FORWARD 100

//variables for auto3
#define THREE_SPIN 1800
#define THREE_FORWARD 1500

//variables for knocking down the post
#define KD_FOREWARD 500
#define KD_LEFT 1000
#define KD_SPIN 1000

void init(){
	action("Initializing...");

	//action("-Checking battery:");
	//scrollText("  Ext: %2.1f",externalBatteryAvg/1000);
	//if(externalBatteryAvg==-1)
	//	error("EXT BATTERY DISCONNECTED");
	//else if(externalBatteryAvg<EXT_LOW)
	//	error("EXT BATTERY LOW");
	//scrollText("  NXT: %2.1f",nAvgBatteryLevel/1000);
	//if(nAvgBatteryLevel<NXT_LOW)
	//	error("NXT BATTERY LOW");

	action("-Resetting encoders...");
	nMotorEncoder[wheelA]=0;
	nMotorEncoder[wheelB]=0;
	nMotorEncoder[wheelC]=0;
	nMotorEncoder[wheelD]=0;
	nMotorEncoder[liftMotor]=0;
	action("  Done");
	action("-Init. Servos...");
	servoChangeRate[dumpServo]=1;
	servo[dumpServo]=HOLD_POS;
	servo[leftIRServo]=LEFT_SERVO_POS;
	servo[rightIRServo]=RIGHT_SERVO_POS;
	servo[rightHook]=RIGHT_HOOK_DOWN;
	action("  Done");
	wait1Msec(100);
	action("-Raising Lift...");
	raise(LIFT_BOTTOM);
	action("  Done");
	wait1Msec(100);
	action("-Done.");
}

void knockdownBalls() {
	driveForward(KD_FOREWARD);
	goLeft(KD_LEFT);
	spinRight(KD_SPIN);
}

task main() {
	action("Waiting...");
	//waitForStart();
	init();
	action("Moving to IR...");
	driveForward(FORWARD_DRIVE);
	action("Checking IR...");
	switch(getCenterThingPos()) {
	case 1:
		action(" Pos 1.");
		goLeft(ONE_LEFT_DRIVE);
		driveForward(ONE_FORWARD_DRIVE);
		break;
	case 2:
		action(" Pos 2.");
		goLeft(TWO_LEFT);
		spinLeft(TWO_SPIN);
		driveForward(TWO_FORWARD);
		break;
	case 3:
		action(" Pos 3.");
		spinLeft(THREE_SPIN);
		driveForward(THREE_FORWARD);
		// may not need realign for close dump
		break;
	default:
		return;
	}
	wait1Msec(250);
	realign();
	tilt();
	raise(HIGH_GOAL);
	dump();
	lower();
	Stop();
	wait1Msec(100000);
	//knockdownBalls();
}
