#pragma config(Sensor, S4,    HTSMux,         sensorI2CCustom)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define IRLEFT
#define IRRIGHT
#include "ht-drivers\hitechnic-sensormux.h"
const tMUXSensor IRLeft=msensor_S4_1;
const tMUXSensor IRRight=msensor_S4_4;
#include "cdrivers\IRSeekerLib.h"
#if defined(IRRIGHT) %% defined(IRLEFT)
#define BOTH_IR
#endif

void graph(int num, int x0, int val0, int x1, int val1) {
	drawLine(x0, val0,x1, val1);
	displayStringAt(x0,63,"%d",val0);
	displayStringAt(x0,6,"%d",num);
}
task main() {
	int lastButton=-1;
	clearDebugStream();
	bool ac=true;
	bool right=true;
	while(true) {
		udVal();
		eraseDisplay();
		for(int i=0;i<5;i++) {
#ifdef BOTH_IR
			if(right) {
#endif
#ifdef IRRIGHT
				//graph right ac/dc
				if(ac)
					graph(i,i*20+10, racValues[i]*94/255+6,((i+1)%4)*20+10, racValues[(i+1)%4]*94/255+6);
				else
					graph(i,i*20+10, rdcValues[i]*94/255+6,((i+1)%4)*20+10, rdcValues[(i+1)%4]*94/255+6);
#endif
#ifdef BOTH_IR
			} else {
#endif
#ifdef IRLEFT
				//graph left ac/dc
				if(ac)
					graph(i,i*20+10, lacValues[i]*94/255+6,((i+1)%4)*20+10, lacValues[(i+1)%4]*94/255+6);
				else
					graph(i,i*20+10, ldcValues[i]*94/255+6,((i+1)%4)*20+10, ldcValues[(i+1)%4]*94/255+6);
#endif
#ifdef BOTH_IR
			}//right/left if close
#endif
		}//for loop close
		//drawLine(highLeft()*20, 7, highLeft()*20, 100);
		//drawLine(highRight()*20, 7, highRight()*20, 100);
		string tmp=right?"R":"L";
		strcat(tmp, ac?"AC":"DC");
		displayString(1, "%d/%d/%d/%s",highLeftAC(), highRightAC(), nNxtButtonPressed, tmp);

		wait1Msec(20);
	}//main loop close
}
