#pragma config(Sensor, S4,    HTSMux,         sensorI2CCustom)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define IRLEFT
#define IRRIGHT
#include "ht-drivers\hitechnic-sensormux.h"
const tMUXSensor IRLeft=msensor_S4_1;
const tMUXSensor IRRight=msensor_S4_4;
#include "cdrivers\IRSeekerLib.h"
#define bwc(test, value) test&value==value

void graph(int num, int x0, int val0, int x1, int val1) {
	drawLine(x0, val0,x1, val1);
	displayStringAt(x0,63,"%d",val0);
	displayStringAt(x0,6,"%d",num);
}
task main() {
	if(!IRSetup())
		return;

	clearDebugStream();
	while(true) {
		bool right = bwc(nNxtButtonPressed,1);
		bool ac = (bwc(nNxtButtonPressed,2);
		udVal();
		eraseDisplay();
		for(int i=0;i<5;i++){
#if defined(IRRIGHT) && defined(IRLEFT)
			if(right)
#endif
#ifdef IRRIGHT
				if(ac)
					graph(i,i*20+10, racValues[i]*94/255+6,((i+1)%4)*20+10, racValues[(i+1)%4]*94/255+6);
				else
					graph(i,i*20+10, rdcValues[i]*94/255+6,((i+1)%4)*20+10, rdcValues[(i+1)%4]*94/255+6);
#endif
#if defined(IRRIGHT) && defined(IRLEFT)
			else
#endif
#ifdef IRLEFT
				if(ac)
					graph(i,i*20+10, lacValues[i]*94/255+6,((i+1)%4)*20+10, lacValues[(i+1)%4]*94/255+6);
				else
					graph(i,i*20+10, ldcValues[i]*94/255+6,((i+1)%4)*20+10, ldcValues[(i+1)%4]*94/255+6);
#endif

			//	drawLine((i-1)*20+10, ldcValues[i-1]*94/255+6,(i)*20+10, ldcValues[i]*94/255+6);
			//drawLine((i-1)*20, rValues[i-1]*96/255+6,(i)*20, rValues[i]*96/255+6);
		}
		//drawLine(highLeft()*20, 7, highLeft()*20, 100);
		//drawLine(highRight()*20, 7, highRight()*20, 100);
		displayString(1, "%d/%d/%d",highLeftAC(), highRightAC(), nNxtButtonPressed);

		wait1Msec(20);
	}
}
