#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ht-drivers\hitechnic-sensormux.h"
#include "ht-drivers\lego-ultrasound.h"
const tMUXSensor UltraLeft = msensor_S4_2;
const tMUXSensor UltraRight = msensor_S4_3;
task main() {

	while(true){
		int ldst=USreadDist(UltraLeft);
		int rdst=USreadDist(UltraRight);
		displayTextLine(2, "L: %d R: %d", ldst, rdst);
		bool lbl = ldst<20;
		bool rbl = rdst<20;
		if(lbl&&rbl)
			displayCenteredTextLine(3,"OK");
		else if(lbl)
			displayCenteredTextLine(3,"<-");
		else if(rbl)
			displayCenteredTextLine(3,"->");
		else
			displayCenteredTextLine(3,"BAD");
		wait1Msec(50);
	}
}
