#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     HTSMUX,         sensorI2CCustom)
#pragma config(Motor,  motorA,          sweeperA,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          sweeperB,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          heartbeat,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     wheelC,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     wheelD,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     wheelB,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     wheelA,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     collectorMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     liftMotor,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    dumpServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    rightIRServo,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    leftIRServo,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "libAuto.c"
const int speed=50;
const tMUXSensor UltraLeft = msensor_S4_2;
const tMUXSensor UltraRight = msensor_S4_3;
int statRead(tMUXSensor uc, int samples) {
	//array of readings
	int[samples] readings;
	for(int i=0;i<samples;i++) {
		readings[i]=USreadDist(uc);
		wait1Msec(10);
	}
	//sort array
	for (int i = 0, j = 0; i < samples; i+=((j<samples)?0:(j=i+1)))
		if (readings[i] > readings[j]) {
			int tmp = readings[i];
			readings[i] = readings[j];
			readings[j] = tmp;
		}
	return readings[samples/2];
}
task main() {
	bDisplayDiagnostics=false;
	while(true){
		int ldst=statRead(UltraLeft, 10);
		int rdst=statRead(UltraRight, 10);
		displayTextLine(2, "L: %d R: %d", ldst, rdst);
		bool lbl = ldst<40;
		bool rbl = rdst<40;
		if(lbl&&rbl){
			displayCenteredTextLine(3,"OK");
			cDir(0,0,0,0);
		}else if(lbl){
			displayCenteredTextLine(3,"<-");
			cDir(-speed,-speed,speed,speed);
		}else if(rbl){
			displayCenteredTextLine(3,"->");
			cDir(speed,speed,-speed,-speed);
		}else{
			displayCenteredTextLine(3,"BAD");
		}
		wait1Msec(10);
	}
}
